cc_test (
    name = "pwm_test",
    srcs = [
        "pwm_test.cc",
    ],
    deps = [
        "//tareeq/gpio:gpio",
	"//tareeq/mocks:gpio_mocks",
        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
)